### ISSUE TITLE
app更新不了

### ISSUE THREAD

**Issue by suzuha0927** [pcrgvg/pcrgvg_flutter#1]
更新页面显示“File size exceeded the configured limit of 20 MB.”

**Comment by zafkielkurumi** [comment]
试试 我的→ 关于→ 下载最新app

**Comment by zafkielkurumi** [comment]
更新了新版本， 网页下载最新版或者在 关于中 点击下载最新app安装



> 更新页面显示“File size exceeded the configured limit of 20 MB.”
