### ISSUE TITLE
安装提示更新，更新之后还是这个版本

### ISSUE THREAD

**Issue by dfmjndm** [pcrgvg/pcrgvg_flutter#2]
显示从作业网下到的安装包
![Screenshot_2022-04-26-01-09-16-371_com.kurumi.pcrgvg_flutter.jpg](https://user-images.githubusercontent.com/57401901/165139107-984fbcb3-43e5-4ed4-bb42-46315b70f6ee.jpg)
打开提示要更新数据库和软件，数据库点更新，提示更新完成，一刷新，没数据。
点更新软件，先是到cdn.jsdelivr，下到的包就是还是这个版本，然后点下面那个下载最新app，跳到了阿里云的oss，还是这个1.0.0+10版本
![Screenshot_2022-04-26-01-09-22-303_com.kurumi.pcrgvg_flutter.jpg](https://user-images.githubusercontent.com/57401901/165139675-76fe32a7-cdb0-4cac-9ced-411d0c054c68.jpg)![Screenshot_2022-04-26-01-09-28-065_com.kurumi.pcrgvg_flutter.jpg](https://user-images.githubusercontent.com/57401901/165139689-3532ce6f-3981-482a-a293-0a3f4a47136b.jpg)

**Comment by dfmjndm** [comment]
Git上面的+12下下来是+11的包

**Comment by zafkielkurumi** [comment]
> Git上面的+12下下来是+11的包

中间是作业，左边是收藏，版本更新我之后会看看，+10版本1 2阶段未合并查不出作业，3 4阶段正常

**Comment by zafkielkurumi** [comment]
> Git上面的+12下下来是+11的包

已发布+15版本，点击下载最新app更新
