### ISSUE TITLE
16版本小米无法识别，错误108

### ISSUE THREAD

**Issue by lan493** [pcrgvg/pcrgvg_flutter#4]
如题

**Comment by zafkielkurumi** [comment]
把手机设置成允许未知来源的安装包后试试

**Comment by lan493** [comment]
还是没用，放弃了，手机是k50pro 版本MIUI13.0.13

**Comment by zafkielkurumi** [comment]
> 还是没用，放弃了，手机是k50pro 版本MIUI13.0.13

以前版本的app能装上吗，还是这是第一次用？ 然后提供下安装失败那里报错的截图

**Comment by zafkielkurumi** [comment]
> 还是没用，放弃了，手机是k50pro 版本MIUI13.0.13

可以下载最新+17版本，已添加支持android12
