### ISSUE TITLE
iOS版显示testflight到期，无法使用

### ISSUE THREAD

**Issue by botsukanoai** [pcrgvg/pcrgvg_flutter#5]
无法更新和使用，在网站上点击ios下载也显示为“此beta版不接受新的测试人员”
![0B8FEFE5-13BB-4E8D-9918-AC648B5C6814](https://user-images.githubusercontent.com/116990256/198861488-8f8ed4fb-aff9-4648-a049-cb1b161bff31.jpeg)

![86665FC9-A2A3-46CE-B83B-CF6F9A3D919F](https://user-images.githubusercontent.com/116990256/198861460-f85c4f33-c632-4eb0-94a3-336ddfa4de5e.png)

**Comment by swearl** [comment]
一样…会战最后一天才打不开…

**Comment by zafkielkurumi** [comment]
重新更新就行了
