### ISSUE TITLE
ios beta已過期重新掃QR Code顯示目前暫不接受任何新測試人員

### ISSUE THREAD

**Issue by chen449** [pcrgvg/pcrgvg_flutter#7]
如圖
![IMG_1644](https://github.com/user-attachments/assets/bb6171e5-a60f-4369-b185-edacdc1570de)

**Comment by zafkielkurumi** [comment]
由于维护IOS版本的开发者的Testflight过期，不再维护了

**Comment by zafkielkurumi** [comment]
由于维护IOS版本的开发者的Testflight过期，不再维护了， IOS版本后续也停止维护
